### PR TITLE
Feature/blazor webassembly ga3.2.0

### PR DESCRIPTION
**Pull request by kpkrish**
I wasn't able to find the specific issue you reported. However since I started working on this already, I upgraded all references to latest stable. All tests pass. Hope this resolves all issues.

### CODE REVIEW

**Comment by mrpmorris** [comment]
I must have had a hiccup on my laptop. I checked out your PR again and this time I couldn't see any preview packages in use.

I've merged this into release/3.1.2

Thank you very much for your time and efforts on this!

**Comment by mrpmorris** [comment]
@kpkrish erm... I don't suppose you'd be willing to do the same to https://github.com/mrpmorris/blazor-university would you? :)

**Comment by kpkrish** [comment]
> I must have had a hiccup on my laptop. I checked out your PR again and this time I couldn't see any preview packages in use.
> 
> I've merged this into release/3.1.2
> 
> Thank you very much for your time and efforts on this!

Thank you for your patience & helping me make my first contribution to open source :-) Cheers.

**Comment by kpkrish** [comment]
> @kpkrish erm... I don't suppose you'd be willing to do the same to https://github.com/mrpmorris/blazor-university would you? :)

@mrpmorris  :-) I will be happy to try bumping up all references to latest in blazor-university. 
I didn't find any tests there so I will only bump it up & ensure that build is successful.
I will leave it to your experience & wisdom to merge only whatever commits you find acceptable.

I appreciate your patience & liked working with you. I think I may be able to learn few new tricks if I continue to work with you, so I can help you write few test as well. I'm not promising tests, I will attempt only if & when time permits.

Do you have an id to PM like slack, skype etc ? so I can ping you if I hit a brick wall with your code.
Cheers.

**Comment by mrpmorris** [comment]
That's great, thank you!

Is just like the bare minimum. Package numbers corrected, please. 

You can get hold of me here https://gitter.im/aspnet/Blazor

**Comment by kpkrish** [comment]
> That's great, thank you!
> 
> Is just like the bare minimum. Package numbers corrected, please.
> 
> You can get hold of me here https://gitter.im/aspnet/Blazor

Cool, getting it to GA 3.2.0 should not be a big problem. I will give it it a shot & reach out to you if I get stuck.

**Pull request merged**
