### PR TITLE
Release/5.0

### PR DESCRIPTION
**Pull request by mrpmorris**

### CODE REVIEW

**Comment by lucaswalter** [comment]
@mrpmorris Anything else we can do in terms of reviewing & testing here? We are very interested in being able to pull in the fluxor initialization changes.

**Comment by rodrigochapeta** [comment]
Hi @mrpmorris,
This looks great, keen on the change to *is/ is not* operators, look forward to this release

**Comment by uhfath** [comment]
This looks promising!
However, one question, @mrpmorris.
Will it be possible to 'select' multiple values in a state selector?
With multiple `Select` calls or through an anonymous object?

**Comment by mrpmorris** [comment]
A state selector will only have a single selector.

**Comment by uhfath** [comment]
Thanks. Is there any particular reason for this?

**Comment by mrpmorris** [comment]
It's a strongly-typed generic, so it takes `<TState, TSubSelectionOfThatState>` as generic parameters. So you need one per selection otherwise I'd have to have `<TState1, TSelection1, TState2, TSelection2, TState3, TSelection3>` along with properties `State1`, `State2`, `State3` etc.

It quickly becomes unwieldy, and is far simpler to have multiple injected properties in the component instead.

**Comment by uhfath** [comment]
> It quickly becomes unwieldy, and is far simpler to have multiple injected properties in the component instead.
That's a good point. Thanks for the info.
Looking forward to take a look.

**Pull request merged**
