### PR TITLE
Feature/blazor webassembly ga3.2.0

### PR DESCRIPTION
**Pull request by kpkrish**
All done. Ready for merge

### CODE REVIEW

**Comment by mrpmorris** [comment]
Looks good. I'll download and check it in VS later today and get back to you :)

**Comment by mrpmorris** [comment]
The following assemblies are still referenced via a release-candidate version.

Components.WebAssembly
WebAssembly.Build
WebAssembly.DevServer

If you right-click the solution, select "Manage NuGet packages for solution", then click the [Installed] tab you'll see the installed versions.

**Comment by kpkrish** [comment]
Had a hectic day yesterday will resolve this today. Thanks

**Comment by kpkrish** [comment]
I looked at NuGet packages for solution and everything looks good to me. Screen shot attached. Can you please send your screen shot ?

To double check, In Visual studio, I did a find in files *.csproj and confirmed that the 3 assemblies are all at Version="3.2.0"
Components.WebAssembly
WebAssembly.Build
WebAssembly.DevServer

I even did a grep for "preview" & found 0 occurrences.

Please send your screen shot ?
devenv_eeWkHxVYJs

**Pull request closed without merging**
