### PR TITLE
#308

### PR DESCRIPTION
**Pull request by GiannhsR**
Possible fix for #308 $(Configuration)=='Debug'

### CODE REVIEW

**Comment by mrpmorris** [comment]
Thanks!

You seem to have merge conflicts. Did you remember to pull first?

**Comment by GiannhsR** [comment]
I  forked the main branch, created a new branch named #308_typofix.
I didn't get a conflict warning while updating the readme.md.
Currently, I get 
image
Is there a way for me to resolve the conflicts?

**Comment by mrpmorris** [comment]
It looks like you've merged 5.4 into your branch rather than basing off 5.4, this seems to be showing that your PR includes the changes of other people and I'm not sure what the result of the merge will look like.

Would you mind checking out the release/5.4 branch itself and making the change in that before submitting that branch as a PR instead? I'm sorry it's turning out to be a lot of work :)

**Comment by GiannhsR** [comment]
I have submitted a new PR #311

**Pull request closed without merging**
