### PR TITLE
Add component hook for state change

### LINKED ISSUE #62: Render before StateChanged
I would like to copy something from state to a local property so I can bind to it without modifying state directly. A later event will send the local copy back to state via an action.

If I use `IState.StateChanged` to do this, I sometimes get a render before the `StateChanged` event is fired. This makes mixing state with local properties problematic as it can produce scenarios not covered by tests.

For example, in the page below, the last paragraph should never show, but occasionally does.

    @page "/customers/{id:int}"
    @using Fluxor
    @using FluxorGap.Data
    @using FluxorGap.Store.EditCustomer
    @inherits Fluxor.Blazor.Web.Components.FluxorComponent

    @if (State.Value.IsLoading) {
        <p><em>Loading...</em></p>
    }
    else if (Customer != null) {
        <p>Customer form here</p>
    }
    else {
        <p style="color: red;"><strong>THIS SHOULD NEVER SHOW</strong></p>
    }

    @code {
        [Parameter]
        public int Id { get; set; }

        [Inject]
        private IState<State> State { get; set; }

        [Inject]
        private IDispatcher Dispatcher { get; set; }

        private Customer Customer { get; set; }

        protected override void OnInitialized()
        {
            base.OnInitialized();

            State.StateChanged += StateOnStateChanged;

            Dispatcher.Dispatch(new GetCustomerAction(Id));
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
                State.StateChanged -= StateOnStateChanged;
            
            base.Dispose(disposing);
        }

        private void StateOnStateChanged(object sender, State state)
        {
            Customer = state.Customer?.Clone();
            StateHasChanged();
        }
    }

Is there another way to copy state immediately after an effect?

[fluxor-gap.zip](https://github.com/mrpmorris/Fluxor/files/5020785/fluxor-gap.zip)

### PR DESCRIPTION
**Pull request by deadtoadroad**
Add a hook for receiving state changes. Fixes #62.

### CODE REVIEW

**Comment by mrpmorris** [comment]
Thanks. What are you intending to use this for?

**Comment by mrpmorris** [comment]
I'm not going to merge this one in because I don't like the addition of the method.

**Comment by deadtoadroad** [comment]
Will there be another way to copy state locally? In the case of binding to objects in forms, being able to copy state should be an easy process, one that doesn't rely on creating and disposing event handlers, or rely on the arbitrary execution order of those event handlers for bug free operation.

In defense of the new method, it seems consistent to me with the lifecycle events of a Blazor component. It's similar to overriding `OnInitialized` or `OnAfterRender`. Subscribing (and unsubscribing) to an event in a Blazor component directly is not as consistent.

**Comment by mrpmorris** [comment]
Have a look at this and comment with your thoughts https://github.com/mrpmorris/Fluxor/issues/66

**Comment by deadtoadroad** [comment]
@mrpmorris Thanks, will do.

**Pull request closed without merging**
